### ISSUE TITLE
Error when getting assets

### ISSUE THREAD

**Issue by modbender** [dev-josias/expo-music-library#2]
When running on Android 14 Pixel 8 API 34, I get the following error

![image](https://github.com/user-attachments/assets/da97d10a-c323-4bca-b4dc-9dc93cf304f7)

The code is as below:
```js
MusicLibrary.getAssetsAsync({ first: 10, mediaType: ['audio'] }).then(
  (assets) => {
    console.log('Assets:', assets);
  }
);
```

```json
"expo": "^51.0.24",
```

Of course I have tried running it as given in README too.

**Comment by dev-josias** [comment]
> When running on Android 14 Pixel 8 API 34, I get the following error
> 
> ![image](https://private-user-images.githubusercontent.com/25717245/367442279-da97d10a-c323-4bca-b4dc-9dc93cf304f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTE5NjcsIm5iZiI6MTcyNjY1MTY2NywicGF0aCI6Ii8yNTcxNzI0NS8zNjc0NDIyNzktZGE5N2QxMGEtYzMyMy00YmNhLWI0ZGMtOWRjOTNjZjMwNGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5Mjc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YmRiYjE1NDI0MzM5ODZiN2UyMTg4NDEwMDI0MjI2Zjg1NWQ4ODFkNjRlOGRlNDhlZWFjYTdlOWU3ZmRjNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._XNkowyTZKHCwxrmyCkAqoS1Pr7QAPXcOmyeDBFm0eI)
> 
> The code is as below:
> 
> ```js
> MusicLibrary.getAssetsAsync({ first: 10, mediaType: ['audio'] }).then(
>   (assets) => {
>     console.log('Assets:', assets);
>   }
> );
> ```
> 
> ```json
> "expo": "^51.0.24",
> ```
> 
> Of course I have tried running it as given in README too.

Try using that until I fix the issue. add ``` { sortBy: 'default' } ``` to the options. 
```js
MusicLibrary.getAssetsAsync({ first: 10, sortBy: 'default', mediaType: ['audio'] }).then(
  (assets) => {
    console.log('Assets:', assets);
  }
);
```

**Comment by dev-josias** [comment]
it's fixed now @modbender

**Comment by modbender** [comment]
Thank you, though I haven't verified it.
